title: Khairunnisa Aulia Rahma
logo: /main/cropped-Khairunnisa%20Aulia%20Rahma-13422112-Teknik%20Industri.png
decription:  I am deeply passionate about business consulting, data analytics, and machine learning, leveraging innovative solutions to drive impactful decision-making.
show_downloads: true
theme: jekyll-theme-minimal
