title: Khairunnisa Aulia Rahma
logo: cropped-Khairunnisa Aulia Rahma-13422112-Teknik Industri.png
decription:  I am deeply passionate about business consulting, data analytics, and machine learning, leveraging innovative solutions to drive impactful decision-making.
show_downloads: true
theme: jekyll-theme-minimal

